#服务器配置
server:
  port: 8080

#数据库配置
spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/manageplatform?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
     username: root
     password: long_1989
     # 使用druid数据源
     type: com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.jdbc.Driver
     filters: stat
     maxActive: 20
     initialSize: 1
     maxWait: 60000
     minIdle: 1
     timeBetweenEvictionRunsMillis: 60000
     minEvictableIdleTimeMillis: 300000
     validationQuery: select 'x'
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     poolPreparedStatements: true
     maxPoolPreparedStatementPerConnectionSize: 20
     maxOpenPreparedStatements: 20
  #freemarker配置
  freemarker:
    allow-request-override: false
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: ["classpath:/templates/"]


#mybatis配置
mybatis:
  mapper-locations: classpath:mybatis-mapper/*.xml
  type-aliases-package: com.eleven.manage.platform.mybatis.model

mapper:
  mappers:  com.eleven.manage.platform.mybatis.dao
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check




